-- Table de référence des SKU (code produit) et de leur nom/descriptif,
-- reprise de la liste fournie par l'équipe produit (366 lignes) — sert de
-- référentiel consultable dans l'app, indépendant des gabarits/catégories
-- déjà en place (un même SKU n'est pas forcément lié à un seul gabarit).
-- `group_label` reprend le regroupement de la liste source (ex. "Tasses +
-- Tumblers", "Impressions - Toiles / Canvas").
-- À exécuter dans Supabase : Dashboard > SQL Editor > coller ce fichier > Run

create table if not exists public.skus (
  id uuid primary key default gen_random_uuid(),
  sku text not null unique,
  name text not null,
  group_label text not null,
  created_at timestamptz not null default now()
);

alter table public.skus enable row level security;

create policy "Les employés lisent les skus" on public.skus
  for select using (auth.role() = 'authenticated');
create policy "Les employés créent des skus" on public.skus
  for insert with check (auth.role() = 'authenticated');
create policy "Les employés modifient des skus" on public.skus
  for update using (auth.role() = 'authenticated');
create policy "Les employés suppriment des skus" on public.skus
  for delete using (auth.role() = 'authenticated');

-- Import initial depuis Listes_Produits_SKU-12mai2026.pdf. La ligne
-- "???? / Lots de 4 aimants" du PDF n'a pas de code SKU réel et est exclue.
insert into public.skus (sku, name, group_label) values
  ('imp-2_5x4-1side', 'Papeterie - 2,5 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-2_5x4-RV', 'Papeterie - 2,5 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-2x6-1side', 'Papeterie - 2 x 6 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-2x6-RV', 'Papeterie - 2 x 6 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-3_5x8-1side', 'Papeterie - 3,5 x 8 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-3_5x8-RV', 'Papeterie - 3,5 x 8 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-3_75x8_25-1side', 'Papeterie - 3,75 x 8,25 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-3_75x8_25-RV', 'Papeterie - 3,75 x 8,25 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-3x3-1side', 'Papeterie - 3 x 3 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-3x3-RV', 'Papeterie - 3 x 3 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4_25x5_5-1side', 'Papeterie - 4,25 x 5,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4_25x5_5-RV', 'Papeterie - 4,25 x 5,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x11-1side', 'Papeterie - 4 x 11 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x11-RV', 'Papeterie - 4 x 11 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x2_5-1side', 'Papeterie - 4 x 2,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x2_5-RV', 'Papeterie - 4 x 2,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x4-1side', 'Papeterie - 4 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x4-RV', 'Papeterie - 4 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x5-1side', 'Papeterie - 4 x 5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x5-RV', 'Papeterie - 4 x 5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x6-1side', 'Papeterie - 4 x 6 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x6-RV', 'Papeterie - 4 x 6 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-4x9-1side', 'Papeterie - 4 x 9 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-4x9-RV', 'Papeterie - 4 x 9 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-5_5x4_25-1side', 'Papeterie - 5,5 x 4,25 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-5_5x4_25-RV', 'Papeterie - 5,5 x 4,25 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-5_5x8_25-1side', 'Papeterie - 5,5 x 8,25 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-5_5x8_25-RV', 'Papeterie - 5,5 x 8,25 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-5x4-1side', 'Papeterie - 5 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-5x4-RV', 'Papeterie - 5 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-5x5-1side', 'Papeterie - 5 x 5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-5x5-RV', 'Papeterie - 5 x 5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-5x7-1side', 'Papeterie - 5 x 7 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-5x7-RV', 'Papeterie - 5 x 7 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-6x2-1side', 'Papeterie - 6 x 2 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-6x2-RV', 'Papeterie - 6 x 2 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-6x4-1side', 'Papeterie - 6 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-6x4-RV', 'Papeterie - 6 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-6x6-1side', 'Papeterie - 6 x 6 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-6x6-RV', 'Papeterie - 6 x 6 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-7x5-1side', 'Papeterie - 7 x 5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-7x5-RV', 'Papeterie - 7 x 5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8_25x3_75-1side', 'Papeterie - 8,25 x 3,75 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8_25x3_75-RV', 'Papeterie - 8,25 x 3,75 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8_5x11-1side', 'Papeterie - 8,5 x 11 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8_5x11-RV', 'Papeterie - 8,5 x 11 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8_5x14-1side', 'Papeterie - 8,5 x 14 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8_5x14-RV', 'Papeterie - 8,5 x 14 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8_25x5_5-1side', 'Papeterie - 8,25 x 5,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8_25x5_5-RV', 'Papeterie - 8,25 x 5,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8x3_5-1side', 'Papeterie - 8 x 3,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8x3_5-RV', 'Papeterie - 8 x 3,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-8x8-1side', 'Papeterie - 8 x 8 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-8x8-RV', 'Papeterie - 8 x 8 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-9x4-1side', 'Papeterie - 9 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-9x4-RV', 'Papeterie - 9 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-10x10-1side', 'Papeterie - 10 x 10 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-10x10-RV', 'Papeterie - 10 x 10 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-11x17-1side', 'Papeterie - 11 x 17 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-11x17-RV', 'Papeterie - 11 x 17 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-11x4-1side', 'Papeterie - 11 x 4 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-11x4-RV', 'Papeterie - 11 x 4 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-11x8_5-1side', 'Papeterie - 11 x 8,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-11x8_5-RV', 'Papeterie - 11 x 8,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-14x8_5-1side', 'Papeterie - 14 x 8,5 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-14x8_5-RV', 'Papeterie - 14 x 8,5 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('imp-17x11-1side', 'Papeterie - 17 x 11 pouces / 1 côté', 'Impressions - Papiers / Cartons'),
  ('imp-17x11-RV', 'Papeterie - 17 x 11 pouces / Recto - Verso', 'Impressions - Papiers / Cartons'),
  ('print-4x6-satin', 'Photo - 4 x 6 satiné', 'Photos - Impressions'),
  ('print-5x7-satin', 'Photo - 5 x 7 satiné', 'Photos - Impressions'),
  ('print-8x10-satin', 'Photo - 8 x 10 satiné', 'Photos - Impressions'),
  ('print-8x12-satin', 'Photo - 8 x 12 satiné', 'Photos - Impressions'),
  ('print-10x10-satin', 'Photo - 10 x 10 satiné', 'Photos - Impressions'),
  ('print-10x13-satin', 'Photo - 10 x 13 satiné', 'Photos - Impressions'),
  ('print-10x15-satin', 'Photo - 10 x 15 satiné', 'Photos - Impressions'),
  ('print-11x14-satin', 'Photo - 11 x 14 satiné', 'Photos - Impressions'),
  ('print-12x12-satin', 'Photo - 12 x 12 satiné', 'Photos - Impressions'),
  ('print-12x16-satin', 'Photo - 12 x 16 satiné', 'Photos - Impressions'),
  ('print-12x18-satin', 'Photo - 12 x 18 satiné', 'Photos - Impressions'),
  ('print-16x20-satin', 'Photo - 16 x 20 satiné', 'Photos - Impressions'),
  ('print-16x24-satin', 'Photo - 16 x 24 satiné', 'Photos - Impressions'),
  ('print-20x24-satin', 'Photo - 20 x 24 satiné', 'Photos - Impressions'),
  ('print-20x30-satin', 'Photo - 20 x 30 satiné', 'Photos - Impressions'),
  ('print-24x30-satin', 'Photo - 24 x 30 satiné', 'Photos - Impressions'),
  ('print-24x36-satin', 'Photo - 24 x 36 satiné', 'Photos - Impressions'),
  ('print-30x40-satin', 'Photo - 30 x 40 satiné', 'Photos - Impressions'),
  ('print-36x60-satin', 'Photo - 36 x 60 satiné', 'Photos - Impressions'),
  ('print-40x60-satin', 'Photo - 40 x 60 satiné', 'Photos - Impressions'),
  ('print-44x60-satin', 'Photo - 44 x 60 satiné', 'Photos - Impressions'),
  ('TE-Bl-12oz', 'Tasse Émaille - Blanc - 12 oz', 'Tasses + Tumblers'),
  ('TCBP-Go-11oz', 'Tasse Céramique Bord & Poignée - Doré - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Bf-11oz', 'Tasse Céramique Intérieur & Poignée - Bleu Foncé - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Bp-11oz', 'Tasse Céramique Intérieur & Poignée - Bleu Pâle - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Ja-11oz', 'Tasse Céramique Intérieur & Poignée - Jaune - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Nr-11oz', 'Tasse Céramique Intérieur & Poignée - Noir - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Og-11oz', 'Tasse Céramique Intérieur & Poignée - Orange - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Rg-11oz', 'Tasse Céramique Intérieur & Poignée - Rouge - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Rs-11oz', 'Tasse Céramique Intérieur & Poignée - Rose - 11 oz', 'Tasses + Tumblers'),
  ('TCIP-Vf-11oz', 'Tasse Céramique Intérieur & Poignée - Vert Foncé - 11 oz', 'Tasses + Tumblers'),
  ('TUMB-PC-20oz', 'Gobelet en acier avec paille et couvercle - 20 oz', 'Tasses + Tumblers'),
  ('Pl-Sp-11x5', 'Planificateur à spirales - 11 x 5,5 pouces', 'Articles de Papeterie'),
  ('Pl-Sp-11x8', 'Planificateur à spirales - 11 x 8,5 pouces', 'Articles de Papeterie'),
  ('Ai-Ca-2x2', 'Aimant Carré 2x2 pouces', 'Aimants'),
  ('Ai-Ca-2x2-1x9', 'Aimant Carré 2x2 pouces / 1 aimant 9 fois', 'Aimants'),
  ('Ai-Ca-2x2-9x1', 'Aimant Carré 2x2 pouces / 9 aimants 1 fois', 'Aimants'),
  ('Ai-Ho-10x8', 'Aimant Feuille Horizontal / 10 x 8 pouces', 'Aimants'),
  ('Ai-Ho-6x4', 'Aimant Feuille Horizontal / 6 x 4 pouces', 'Aimants'),
  ('Ai-Ho-7x5', 'Aimant Feuille Horizontal / 7 x 5 pouces', 'Aimants'),
  ('Ai-Ve-4x6', 'Aimant Feuille Vertical / 4 x 6 pouces', 'Aimants'),
  ('Ai-Ve-5x7', 'Aimant Feuille Vertical / 5 x 7 pouces', 'Aimants'),
  ('Ai-Ve-8x10', 'Aimant Feuille Vertical / 8 x 10 pouces', 'Aimants'),
  ('BN-Bo-Ca-Ho', 'Boule Noël- Cadre Horizontal - Bois', 'Ornements'),
  ('BN-Bo-Ca-Ve', 'Boule Noël - Cadre Vertical - Bois', 'Ornements'),
  ('BN-Bo-Fl', 'Boule Noël- Flocon - Bois', 'Ornements'),
  ('BN-Md-Ce', 'Boule Noël - Cercle - MDF', 'Ornements'),
  ('BN-Pl-Fl', 'Boule Noël - Flocon - Plastique', 'Ornements'),
  ('BN-Pl-MB', 'Boule Noël - Mini Boule - Plastique', 'Ornements'),
  ('PC-Md-4x6', 'Porte-Clé MDF / Vertical', 'Porte-Clés'),
  ('PC-Md-6x4', 'Porte-Clé MDF / Horizontal', 'Porte-Clés'),
  ('PC-Pl-1x2', 'Porte-Clé Plastique / Vertical', 'Porte-Clés'),
  ('PC-Pl-2x1', 'Porte-Clé Plastique / Horizontal', 'Porte-Clés'),
  ('Ca-Ho-6x4', 'Cadre Aluminium avec base en bois / Horizontal / 6 x 4 pouces', 'Cadres Plaque Aluminium'),
  ('Ca-Ho-7x5', 'Cadre Aluminium avec base en bois / Horizontal / 7x 5 pouces', 'Cadres Plaque Aluminium'),
  ('Ca-Ve-4x6', 'Cadre Aluminium avec base en bois / Vertical / 4 x 6 pouces', 'Cadres Plaque Aluminium'),
  ('Ca-Ve-5x7', 'Cadre Aluminium avec base en bois / Vertical / 5 x 7 pouces', 'Cadres Plaque Aluminium'),
  ('toiles-panel-08x10', 'Impression sur toile / 08x10', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-08_5x11', 'Impression sur toile / 8,5x11', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-08x12', 'Impression sur toile / 08x12', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-10x08', 'Impression sur toile / 10x08', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-10x10', 'Impression sur toile / 10x10', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-10x12', 'Impression sur toile / 10x12', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-11x14', 'Impression sur toile / 11x14', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-11x08_5', 'Impression sur toile / 11x8,5', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-12x08', 'Impression sur toile / 12x08', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-12x10', 'Impression sur toile / 12x10', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-12x16', 'Impression sur toile / 12x16', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-12x18', 'Impression sur toile / 12x18', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-14x11', 'Impression sur toile / 14x11', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-14x14', 'Impression sur toile / 14x14', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-14x18', 'Impression sur toile / 14x18', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-16x12', 'Impression sur toile / 16x12', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-16x20', 'Impression sur toile / 16x20', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-16x24', 'Impression sur toile / 16x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-16x30', 'Impression sur toile / 16x30', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-16x36', 'Impression sur toile / 16x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-18x12', 'Impression sur toile / 18x12', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-18x14', 'Impression sur toile / 18x14', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-18x24', 'Impression sur toile / 18x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-20x16', 'Impression sur toile / 20x16', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-20x20', 'Impression sur toile / 20x20', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-20x24', 'Impression sur toile / 20x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-20x30', 'Impression sur toile / 20x30', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x16', 'Impression sur toile / 24x16', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x18', 'Impression sur toile / 24x18', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x20', 'Impression sur toile / 24x20', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x24', 'Impression sur toile / 24x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x28', 'Impression sur toile / 24x28', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x32', 'Impression sur toile / 24x32', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-24x36', 'Impression sur toile / 24x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-28x24', 'Impression sur toile / 28x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-30x16', 'Impression sur toile / 30x16', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-30x20', 'Impression sur toile / 30x20', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-30x32', 'Impression sur toile / 30x32', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-30x36', 'Impression sur toile / 30x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-30x40', 'Impression sur toile / 30x40', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-32x24', 'Impression sur toile / 32x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-32x30', 'Impression sur toile / 32x30', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-34x36', 'Impression sur toile / 34x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x16', 'Impression sur toile / 36x16', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x24', 'Impression sur toile / 36x24', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x30', 'Impression sur toile / 36x30', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x34', 'Impression sur toile / 36x34', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x36', 'Impression sur toile / 36x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x40', 'Impression sur toile / 36x40', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-36x48', 'Impression sur toile / 36x48', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-38x40', 'Impression sur toile / 38x40', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-40x30', 'Impression sur toile / 40x30', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-40x36', 'Impression sur toile / 40x36', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-40x38', 'Impression sur toile / 40x38', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-40x40', 'Impression sur toile / 40x40', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-40x42', 'Impression sur toile / 40x42', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-42x40', 'Impression sur toile / 42x40', 'Impressions - Toiles / Canvas'),
  ('toiles-panel-48x36', 'Impression sur toile / 48x36', 'Impressions - Toiles / Canvas'),
  ('alu-panel-08x10', 'Impression sur Alu Panel / 08x10', 'Impressions - Panels - AluPanel'),
  ('alu-panel-08x12', 'Impression sur Alu Panel / 08x12', 'Impressions - Panels - AluPanel'),
  ('alu-panel-10x08', 'Impression sur Alu Panel / 10x08', 'Impressions - Panels - AluPanel'),
  ('alu-panel-10x10', 'Impression sur Alu Panel / 10x10', 'Impressions - Panels - AluPanel'),
  ('alu-panel-10x12', 'Impression sur Alu Panel / 10x12', 'Impressions - Panels - AluPanel'),
  ('alu-panel-11x14', 'Impression sur Alu Panel / 11x14', 'Impressions - Panels - AluPanel'),
  ('alu-panel-12x08', 'Impression sur Alu Panel / 12x08', 'Impressions - Panels - AluPanel'),
  ('alu-panel-12x10', 'Impression sur Alu Panel / 12x10', 'Impressions - Panels - AluPanel'),
  ('alu-panel-12x16', 'Impression sur Alu Panel / 12x16', 'Impressions - Panels - AluPanel'),
  ('alu-panel-12x18', 'Impression sur Alu Panel / 12x18', 'Impressions - Panels - AluPanel'),
  ('alu-panel-14x11', 'Impression sur Alu Panel / 14x11', 'Impressions - Panels - AluPanel'),
  ('alu-panel-14x14', 'Impression sur Alu Panel / 14x14', 'Impressions - Panels - AluPanel'),
  ('alu-panel-14x18', 'Impression sur Alu Panel / 14x18', 'Impressions - Panels - AluPanel'),
  ('alu-panel-16x12', 'Impression sur Alu Panel / 16x12', 'Impressions - Panels - AluPanel'),
  ('alu-panel-16x20', 'Impression sur Alu Panel / 16x20', 'Impressions - Panels - AluPanel'),
  ('alu-panel-16x24', 'Impression sur Alu Panel / 16x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-16x30', 'Impression sur Alu Panel / 16x30', 'Impressions - Panels - AluPanel'),
  ('alu-panel-16x36', 'Impression sur Alu Panel / 16x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-18x12', 'Impression sur Alu Panel / 18x12', 'Impressions - Panels - AluPanel'),
  ('alu-panel-18x14', 'Impression sur Alu Panel / 18x14', 'Impressions - Panels - AluPanel'),
  ('alu-panel-18x24', 'Impression sur Alu Panel / 18x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-20x16', 'Impression sur Alu Panel / 20x16', 'Impressions - Panels - AluPanel'),
  ('alu-panel-20x20', 'Impression sur Alu Panel / 20x20', 'Impressions - Panels - AluPanel'),
  ('alu-panel-20x24', 'Impression sur Alu Panel / 20x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-20x30', 'Impression sur Alu Panel / 20x30', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x16', 'Impression sur Alu Panel / 24x16', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x18', 'Impression sur Alu Panel / 24x18', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x20', 'Impression sur Alu Panel / 24x20', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x24', 'Impression sur Alu Panel / 24x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x28', 'Impression sur Alu Panel / 24x28', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x32', 'Impression sur Alu Panel / 24x32', 'Impressions - Panels - AluPanel'),
  ('alu-panel-24x36', 'Impression sur Alu Panel / 24x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-28x24', 'Impression sur Alu Panel / 28x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-30x16', 'Impression sur Alu Panel / 30x16', 'Impressions - Panels - AluPanel'),
  ('alu-panel-30x20', 'Impression sur Alu Panel / 30x20', 'Impressions - Panels - AluPanel'),
  ('alu-panel-30x32', 'Impression sur Alu Panel / 30x32', 'Impressions - Panels - AluPanel'),
  ('alu-panel-30x36', 'Impression sur Alu Panel / 30x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-30x40', 'Impression sur Alu Panel / 30x40', 'Impressions - Panels - AluPanel'),
  ('alu-panel-32x24', 'Impression sur Alu Panel / 32x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-32x30', 'Impression sur Alu Panel / 32x30', 'Impressions - Panels - AluPanel'),
  ('alu-panel-34x36', 'Impression sur Alu Panel / 34x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x16', 'Impression sur Alu Panel / 36x16', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x24', 'Impression sur Alu Panel / 36x24', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x30', 'Impression sur Alu Panel / 36x30', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x34', 'Impression sur Alu Panel / 36x34', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x36', 'Impression sur Alu Panel / 36x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x40', 'Impression sur Alu Panel / 36x40', 'Impressions - Panels - AluPanel'),
  ('alu-panel-36x48', 'Impression sur Alu Panel / 36x48', 'Impressions - Panels - AluPanel'),
  ('alu-panel-38x40', 'Impression sur Alu Panel / 38x40', 'Impressions - Panels - AluPanel'),
  ('alu-panel-40x30', 'Impression sur Alu Panel / 40x30', 'Impressions - Panels - AluPanel'),
  ('alu-panel-40x36', 'Impression sur Alu Panel / 40x36', 'Impressions - Panels - AluPanel'),
  ('alu-panel-40x38', 'Impression sur Alu Panel / 40x38', 'Impressions - Panels - AluPanel'),
  ('alu-panel-40x40', 'Impression sur Alu Panel / 40x40', 'Impressions - Panels - AluPanel'),
  ('alu-panel-40x42', 'Impression sur Alu Panel / 40x42', 'Impressions - Panels - AluPanel'),
  ('alu-panel-42x40', 'Impression sur Alu Panel / 42x40', 'Impressions - Panels - AluPanel'),
  ('alu-panel-48x36', 'Impression sur Alu Panel / 48x36', 'Impressions - Panels - AluPanel'),
  ('acrylic-panel-08x10', 'Impression sur acrylique / 08x10', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-08x12', 'Impression sur acrylique / 08x12', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-10x08', 'Impression sur acrylique / 10x08', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-10x10', 'Impression sur acrylique / 10x10', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-10x12', 'Impression sur acrylique / 10x12', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-11x14', 'Impression sur acrylique / 11x14', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-12x08', 'Impression sur acrylique / 12x08', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-12x10', 'Impression sur acrylique / 12x10', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-12x16', 'Impression sur acrylique / 12x16', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-12x18', 'Impression sur acrylique / 12x18', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-14x11', 'Impression sur acrylique / 14x11', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-14x14', 'Impression sur acrylique / 14x14', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-14x18', 'Impression sur acrylique / 14x18', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-16x12', 'Impression sur acrylique / 16x12', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-16x20', 'Impression sur acrylique / 16x20', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-16x24', 'Impression sur acrylique / 16x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-16x30', 'Impression sur acrylique / 16x30', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-16x36', 'Impression sur acrylique / 16x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-18x12', 'Impression sur acrylique / 18x12', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-18x14', 'Impression sur acrylique / 18x14', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-18x24', 'Impression sur acrylique / 18x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-20x16', 'Impression sur acrylique / 20x16', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-20x20', 'Impression sur acrylique / 20x20', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-20x24', 'Impression sur acrylique / 20x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-20x30', 'Impression sur acrylique / 20x30', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x16', 'Impression sur acrylique / 24x16', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x18', 'Impression sur acrylique / 24x18', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x20', 'Impression sur acrylique / 24x20', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x24', 'Impression sur acrylique / 24x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x28', 'Impression sur acrylique / 24x28', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x32', 'Impression sur acrylique / 24x32', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-24x36', 'Impression sur acrylique / 24x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-28x24', 'Impression sur acrylique / 28x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-30x16', 'Impression sur acrylique / 30x16', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-30x20', 'Impression sur acrylique / 30x20', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-30x32', 'Impression sur acrylique / 30x32', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-30x36', 'Impression sur acrylique / 30x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-30x40', 'Impression sur acrylique / 30x40', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-32x24', 'Impression sur acrylique / 32x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-32x30', 'Impression sur acrylique / 32x30', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-34x36', 'Impression sur acrylique / 34x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x16', 'Impression sur acrylique / 36x16', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x24', 'Impression sur acrylique / 36x24', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x30', 'Impression sur acrylique / 36x30', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x34', 'Impression sur acrylique / 36x34', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x36', 'Impression sur acrylique / 36x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x40', 'Impression sur acrylique / 36x40', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-36x48', 'Impression sur acrylique / 36x48', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-38x40', 'Impression sur acrylique / 38x40', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-40x30', 'Impression sur acrylique / 40x30', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-40x36', 'Impression sur acrylique / 40x36', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-40x38', 'Impression sur acrylique / 40x38', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-40x40', 'Impression sur acrylique / 40x40', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-40x42', 'Impression sur acrylique / 40x42', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-42x40', 'Impression sur acrylique / 42x40', 'Impressions - Panels - Acrylique'),
  ('acrylic-panel-48x36', 'Impression sur acrylique / 48x36', 'Impressions - Panels - Acrylique'),
  ('mdf-panel-08x10', 'Laminage sur MDF / 08x10', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-08x12', 'Laminage sur MDF / 08x12', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-10x08', 'Laminage sur MDF / 10x08', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-10x10', 'Laminage sur MDF / 10x10', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-10x12', 'Laminage sur MDF / 10x12', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-11x14', 'Laminage sur MDF / 11x14', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-12x08', 'Laminage sur MDF / 12x08', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-12x10', 'Laminage sur MDF / 12x10', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-12x16', 'Laminage sur MDF / 12x16', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-12x18', 'Laminage sur MDF / 12x18', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-14x11', 'Laminage sur MDF / 14x11', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-14x14', 'Laminage sur MDF / 14x14', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-14x18', 'Laminage sur MDF / 14x18', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-16x12', 'Laminage sur MDF / 16x12', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-16x20', 'Laminage sur MDF / 16x20', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-16x24', 'Laminage sur MDF / 16x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-16x30', 'Laminage sur MDF / 16x30', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-16x36', 'Laminage sur MDF / 16x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-18x12', 'Laminage sur MDF / 18x12', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-18x14', 'Laminage sur MDF / 18x14', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-18x24', 'Laminage sur MDF / 18x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-20x16', 'Laminage sur MDF / 20x16', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-20x20', 'Laminage sur MDF / 20x20', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-20x24', 'Laminage sur MDF / 20x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-20x30', 'Laminage sur MDF / 20x30', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x16', 'Laminage sur MDF / 24x16', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x18', 'Laminage sur MDF / 24x18', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x20', 'Laminage sur MDF / 24x20', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x24', 'Laminage sur MDF / 24x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x28', 'Laminage sur MDF / 24x28', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x32', 'Laminage sur MDF / 24x32', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-24x36', 'Laminage sur MDF / 24x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-28x24', 'Laminage sur MDF / 28x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-30x16', 'Laminage sur MDF / 30x16', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-30x20', 'Laminage sur MDF / 30x20', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-30x32', 'Laminage sur MDF / 30x32', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-30x36', 'Laminage sur MDF / 30x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-30x40', 'Laminage sur MDF / 30x40', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-32x24', 'Laminage sur MDF / 32x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-32x30', 'Laminage sur MDF / 32x30', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-34x36', 'Laminage sur MDF / 34x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x16', 'Laminage sur MDF / 36x16', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x24', 'Laminage sur MDF / 36x24', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x30', 'Laminage sur MDF / 36x30', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x34', 'Laminage sur MDF / 36x34', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x36', 'Laminage sur MDF / 36x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x40', 'Laminage sur MDF / 36x40', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-36x48', 'Laminage sur MDF / 36x48', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-38x40', 'Laminage sur MDF / 38x40', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-40x30', 'Laminage sur MDF / 40x30', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-40x36', 'Laminage sur MDF / 40x36', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-40x38', 'Laminage sur MDF / 40x38', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-40x40', 'Laminage sur MDF / 40x40', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-40x42', 'Laminage sur MDF / 40x42', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-42x40', 'Laminage sur MDF / 42x40', 'Impressions - Laminages sur MDF'),
  ('mdf-panel-48x36', 'Laminage sur MDF / 48x36', 'Impressions - Laminages sur MDF'),
  ('folded-5x7-landscape-couche', 'Carte pliée Semi-Lustrée (4 côtés) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('folded-5x7-landscape-mat', 'Carte pliée Matte (4 côtés) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('folded-5x7-portrait-couche', 'Carte pliée Semi-Lustrée (4 côtés) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('folded-5x7-portrait-mat', 'Carte pliée Matte (4 côtés) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('postcard-5x7-landscape-couche', 'Carte postale Semi-Lustrée (Recto / Verso) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('postcard-5x7-landscape-mat', 'Carte postale Matte (Recto / Verso) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('postcard-5x7-portrait-couche', 'Carte postale Semi-Lustrée (Recto / Verso) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('postcard-5x7-portrait-mat', 'Carte postale Matte (Recto / Verso) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('single-sided-5x7-landscape-couche', 'Carte photo Semi-Lustrée (1 côté) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('single-sided-5x7-landscape-mat', 'Carte photo Matte (1 côté) / 7 x 5', 'Cartes ( pliées / postale / 1 côté)'),
  ('single-sided-5x7-portrait-couche', 'Carte photo Semi-Lustrée (1 côté) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('single-sided-5x7-portrait-mat', 'Carte photo Matte (1 côté) / 5 x 7', 'Cartes ( pliées / postale / 1 côté)'),
  ('Ro-Hk', 'Rondelle Hockey', 'Sports'),
  ('Ts-Pr-Ho', 'Tapis Souris Horizontal', 'Informatiques'),
  ('Ts-Pr-Ve', 'Tapis Souris Vertical', 'Informatiques')
on conflict (sku) do nothing;
